import {
  authAxiousInstance,
  axiousInstance,
  axiosMultiPartFormData,
  authAxiousInstance1,
  axiousInstanceNew,
  axiousInstanceNewSignIn,
  axiousInstanceFeed,
  axiosMultiPartFormData1,
  axiosNewData,
  axiosNewData1,
  axiosNewDataSave,
  axiosMultiPartFormDataMem,
  axiousInstanceNew1,
  axiosEventsData1,
  axiosNotifications,
  axiosDonation,
} from './api';

export const endpoints = {
  NIVAAS_OTP_TRIGGER:'nivaas/api/auth/jtuserotp/trigger',
  NIVAAS_SIGN_IN:'nivaas/api/auth/signin',
  NIVAAS_CURRENT_CUSTOMER:'nivaas/api/auth/currentCustomer',
  NIVAAS_PROFILE_PIC:'api/customer/upload',
  NIVAAS_CITY:'jtcity/list',
  NIVAAS_APARTMENT:'jtapartment/nearByApartments',
  NIVAAS_FLAT:'jtflat/flats/available',
  GET_POSTALCODES:'jtpostalcode/list',
  NIVAAS_ONBOARD : 'onboarding/flat/request',
  NIVAAS_NEW_APARTMENT_ONBOARD:'jtapartment/save',
  ADD_PREPAIDMETER:'/prepaidmeter/save',
  GET_APARTMENT_PREPAID_METERS:'prepaidmeter/list',
  UPDATE_PREPAID_METER:'prepaidmeter/update',
  ONBOARD_NEW_FLATS:'jtflat/bulk/onboard',
  USER_DETAILS:'api/customer/userDetails',
};

