
export const endpoints = {
  OTP_TRIGGER:'nivaas/auth/jtuserotp/trigger',
  SIGN_IN:'nivaas/auth/signin',
  CURRENT_CUSTOMER:'nivaas/auth/currentCustomer',
  USER_DETAILS:'user/userDetails',
  PROFILE_PIC:'nivaas/api/customer/upload',

  GET_CITY:'jtcity/list',
  GET_APARTMENT:'jtapartment/nearByApartments',
  GET_FLATS:'jtflat/apartment/flats',
  GET_CUSTOMER_ONBOARD_REQUESTS:'onboarding/requests',
  GET_POSTALCODES:'jtpostalcode/list',
  NIVAAS_ONBOARD : 'onboarding/flat/request',
  NEW_APARTMENT_ONBOARD:'jtapartment/save',
  ADD_PREPAIDMETER:'/prepaidmeter/save',
  GET_APARTMENT_PREPAID_METERS:'prepaidmeter/list',
  UPDATE_PREPAID_METER:'prepaidmeter/update',
  ONBOARD_NEW_FLATS:'jtflat/bulk/onboard',
  UPDATE_ONBOARDED_FLATS_DETAILS:'jtflat/apartment',
  MAINTAINENCE_SAVE:'jtmaintanance/save',
  ADD_CONSUMED_UNITS:'/prepaid-usage/flat/update-consumed',
  USER_SOCIETY_DUES:'society/dues/apartment',
  ADMIN_SOCIETY_DUES:'society/dues/list',
  GET_EXPANCES:'apartment/debit-history/apartment',
  GET_EXPANCES_BY_ID:'apartment/debit-history',
  GET_EXPANCES_PDF:'report/apartment',
  ADD_DEBIT_HISTORY:'apartment/debit-history',
  DELETE_EXPANCES:'apartment/debit-history/apartment',
  UPDATE_DEBIT_HISTORY:'apartment/debit-history',
  ADD_CO_ADMIN:'jtapartment/add/co-admin',
  GET_FLAT_OWNERS:'jtflat',
};
