export const allTexts = {
  appVersion: {
    version: '0.70.0',
  },
  buttonTexts: {
    // place all your button texts here
    start: 'Start Now',
    sigup: ' Sign Up',
    login: 'Log In',
    follow: 'Follow',
    unFollow: 'Following',
    contactUs: 'Contact Us',
    next: 'Next',
    updatePassword: 'Update Password',
    updateProfile: 'Update Profile',
    add: 'Add',
    addevents: 'Add Event',
  },

  headings: {
    // place all your Heading texts here
    verfiyEmail: 'Verify your email Address',
    verfiyPhone: 'Verify your Mobile Number',
    splashTitle: 'Start Explore your Best Temple',
    kovela: 'kovela',
    Addpoojari: 'Add Poojari',
    inputTitles: {
      username: 'userName',
      fName: 'First Name',
      phoneNo: 'Phone Number',
      lastName: 'Last Name',
      email: 'Email',
      Newpassword: 'New Password',
      tName: 'Enter Temple Name',
      tDescription: 'Description',
      tCommunity: 'Community',
      confirmPassword: 'Confirm Password',
      currentPassword: 'Current Password',
      pinCode: 'Pincode',
      line2: 'Line 2',
      line1: 'Line 1',
      line3: 'Line 3',
      addEmployeeId: 'Add Employee Id',
      eventname: 'Event Name',
      pickadate: 'Pick a date for darshan',
      feedevent: 'Add this Event to the Feed',
      password: 'Create Password',
      dateOfBirth: 'Date-of-birth',
      gender: 'Gender',
      gotra: 'Gotra',
      userAddress: 'User Address',
      updateProfile: 'Update Profile',
    },
    accountItems: {
      profile: 'profile',
      bookings: 'my bookings',
      donations: 'my donations',
      temple: 'my temples',
      donation: 'Donations',
      ticketBooking: 'Ticket Bookings',
      poojaTicket: 'Pooja Ticket',
      accmodation: 'Accomodation',
      occasion: 'Occasions',
    },
  },
  placeHolders: {
    fistNamePlace: 'Enter Your First Name',
    otpSend: 'Enter OTP sent to ',
    lastNamePlace: 'Enter Your last name',
    emailPlace: 'Enter Your email',
    passwordPlace: 'Enter Your password',
    confirmPasswordPlace: 'Enter Your confirm password',
    tampleNameP: 'Enter tample name here',
    tampleDescritionP: 'Enter Description here',
    communityP: 'Enter community here',
    pincodeP: 'Enter pincode here',
    line1P: 'Enter line1 here',
    line2P: 'Enter line2 here',
    line3P: 'Enter line3 here',
    poojarimailid: 'place holder email id',
    templeSearc: 'Temple search',
    poojariname: 'Poojari Name',
    username: 'user Name',
  },
  paragraphs: {
    alreadyAccount: 'Already have an account? ',
    dontHaveAccount: 'Don’t have an account?',
    splashDescription:
      'There are many destinations for your holiday schedule or healing for activities',
    loginDescription:
      ' There are many destinations for your holiday schedule or healing for activities',
    joining: 'Add poojari name',
  },
  constants: {
    role: {
      admin: 'ROLE_ADMIN',
      agent: 'ROLE_AGENT',
    },
    roleTypes: {
      admin: 'ROLE_ITEM_ADMIN',
      agent: 'ROLE_ITEM_AGENT',
      cms: 'ROLE_ITEM_CMS',
    },
    noInternet: 'Network Error!',
  },
  tabNames: {
    home: 'NIVAAS',
    search: 'search',
    ticket: 'ticket',
    favorites: 'favorites',
    profile: 'profile',
    eventsScreen: 'EventsScreen',
    kovelareels: 'KovelaReels',
    store: 'Store',
  },
  screenTitles: {},
  screenNames: {
    home: 'Home',
    category: 'Category',
    splash: 'Splash',
    signup: 'Signup',
    signup2: 'Signup2',
    signin: 'Signin',
    bottomTab: 'BottomTab',
    otpScreen: 'OtpScreen',
    homeDetails: 'HomeDetails',
    updatePassword: 'UpdatePassword',
    updateProfile: 'Update Profile',
    myTamples: 'MyTamples',
    addTample: 'AddTample',
    service: 'Services',
    seemore: 'Seemore',
    createPost: 'CreatePost',
    poojari: 'Poojari',
    events: 'Events',
    favlist: 'Favorite',
    occasions: 'Occasions',
    manage: 'Manage',
    calender: 'Calender',
    addevents: 'AddEvents',
    nearByProducts: 'NearByProducts',
    nearByServices: 'NearByServices',
    userFeedScreen: 'UserFeedScreen',
    viewProfile: 'ViewProfile',
    menu: 'Menu',
    addtemplenew: 'AddTempleNew',
    splashscreen: 'Splash_Screen',
    createfeed: 'CreateFeed',
    feed: 'Feed',
    profile: 'Profile',
    mySavedPosts: 'MySavedPosts',
    posts: 'Posts',
    followersmembership: 'FollowersMembership',
    profilemembership: 'ProfileMembership',
    addMembershipDetails: 'AddMemebershipDetails',
    seeall: 'SeeAll',
    nearByTempleSeeAll: 'NearByTemplesSeeAll',
    feeds: 'Feeds',
    notification: 'Notifications',
    viewtempleprofile: 'ViewTempleProfile',
    donations: 'Donations',
    memberShip: 'MemberShip',
    eventsScreen: 'EventsScreen',
    donationslist: 'DonationsList',
    eventDetails: 'EventDetails',
    // forgetPassword: 'ForgetPassword?',
    forgotPasswordOtpScreen: 'ForgotPassword',
    profilememberships: 'ProfileMemberShips',
    invitationScreen: 'InvitationScreen',
    createEvent: 'CreateEvent',
    membershipdetails: 'MemberShipDetails',
    templecrew: 'TempleCrew',
    createFeedDescription: 'CreateFeedDescription',
    // editHightlights: 'EditHighlights',
    // editInfo: 'EditInfo',
    editContribute: 'EditContribute',
    profileDonations: 'ProfileDonations',
    profileMyMemberships: 'ProfileMyMemberships',
    info: 'Info',
    profileEvents: 'Profile_Events',
    savehighlight: 'Save_Highlight',
    communityTemple: 'Create_Community_Temple',
    todoList: 'To_Do_List',
    profilenearbytemples: 'Profile_Near_By_Temples',
    abouttemple: 'AboutTemple',
    templeClass: 'TempleClass',
    templeProfileToDoList: 'TempleProfileToDoList',
    memberlist: 'MemberList',
    artistdonardetailslist: 'Artist_Donar_details_list',
    kovelareels: 'KovelaReels',
    newuserprofile: 'NewUserProfile',
    artistDonorScreen: 'ArtistDonorScreen',
    reelupload: 'ReelUpload',
    communityeventsseeall: 'Community_Events_Seeall',
    store: 'Store',
    detailsscreen: 'Details_Screen',
    addartist: 'AddArtist',
    storeCart:'StoreCart',
    orderConfirmed:'OrderConfirmed',
    productedtails: 'ProductDetails',
    storecategorydetails: 'Store_Category_Details',
    orders: 'Orders',
    likeslist: 'LikesList',
  },
  homeHeader: {
    welcome: 'Welcome ',
  },
  homeTabs: {
    all: 'All',
    nearby: 'Nearby',
    popular: 'Popular',
    mostViewd: 'Most Viewed',
  },
  homeDetail: {
    donation: 'Donation',
    ticketBooking: 'Ticket Booking',
    poojaTicketBooking: 'Pooja Ticket Booking',
    accmodation: 'Accomodation',
  },
  other: {
    follow: 'Follow',
    unfollow: 'Unfollow',
    role: 'role is Required',
    AdminAccess: 'true',
    Donation: 'Donation',
  },
};
