export const allTexts = {
  appVersion: {
    version: '1.0',
  },
  buttonTexts: {
    // place all your button texts here
    start: 'Start Now',
    sigup: ' Sign Up',
    login: 'Log In',
    follow: 'Follow',
    unFollow: 'Following',
    contactUs: 'Contact Us',
    next: 'Next',
    updatePassword: 'Update Password',
    updateProfile: 'Update Profile',
    add: 'Add',
    addevents: 'Add Event',
  },

  headings: {
    // place all your Heading texts here
    discoverMore:'Discover more at Nivaas',
    verfiyEmail: 'Verify your email Address',
    verfiyPhone: 'Verify your Mobile Number',
    splashTitle: 'Start Explore your Best Apartments',
    inputTitles: {
      username: 'userName',
      fName: 'First Name',
      phoneNo: 'Phone Number',
      lastName: 'Last Name',
      email: 'Email',
      Newpassword: 'New Password',
      tName: 'Enter Temple Name',
      tDescription: 'Description',
      tCommunity: 'Community',
      confirmPassword: 'Confirm Password',
      currentPassword: 'Current Password',
      pinCode: 'Pincode',
      line2: 'Line 2',
      line1: 'Line 1',
      line3: 'Line 3',
      addEmployeeId: 'Add Employee Id',
      eventname: 'Event Name',
      pickadate: 'Pick a date for darshan',
      feedevent: 'Add this Event to the Feed',
      password: 'Create Password',
      dateOfBirth: 'Date-of-birth',
      gender: 'Gender',
      gotra: 'Gotra',
      userAddress: 'User Address',
      updateProfile: 'Update Profile',
    },
  },
  placeHolders: {
    fistNamePlace: 'Enter Your First Name',
    otpSend: 'Enter OTP sent to ',
    lastNamePlace: 'Enter Your last name',
    emailPlace: 'Enter Your email',
  },
  paragraphs: {
    discoverNivaas:'Discover Nivaas for comprehensive apartment management with features like maintenance management, and a centralized dashboard for real-time monitoring. ',
    accessAll:'Access all importent announcements notices and cirulers here',
    itemPublished:'No item published yet from your society',
  },
  constants: {
    role: {
      admin: 'ROLE_ADMIN',
      agent: 'ROLE_AGENT',
    },
    roleTypes: {
      admin: 'ROLE_ITEM_ADMIN',
      agent: 'ROLE_ITEM_AGENT',
      cms: 'ROLE_ITEM_CMS',
    },
    noInternet: 'Network Error!',
  },
  tabNames: {
    home: 'Home',
    apartments:'Apartments',
    homes:"Homes",
    buyAndSell:'Buy&Sell',
    services:'Services',
    search: 'search',
  },
  screenTitles: {},
  screenNames: {
    splash: 'Splash',
    signup: 'Signup',
    signup2: 'Signup2',
    signin: 'Signin',
    bottomTab: 'BottomTab',
    otpScreen: 'OtpScreen',
    homeDetails: 'HomeDetails',
    addDetails:'AddDetails',
    home:'Home',
    searchCity:'SearchCity',
    services:'Services',
    searchApartmentBlock:'SearchApartmentBlock',
    userOnBoardingForm:'UserOnBoardingForm',
    newApartmentOnBoard:'NewApartmentOnBoard',
    myAccount:'MyAccount',
    houseHold:'HouseHold',
    orders:'Orders',
    saearchFlatData:'saearchFlatData',
    selectCityOptions:'SelectCityOptions',
    frequentVisitor:"FrequentVisitor",
    addPets:'AddPets',
    maid:'Maid',
    addVehicle:'AddVehicle',
    dailyHelp:'Dailyhelp',
    maidProfile:'MaidProfile',
    eachService:'EachService',
    adminSociety:'AdminSociety',
    prepaidMeter:'PrepaidMeter',
    addPrepaidMeter:'AddPrepaidMeter',
    maintainenceSettings:'MaintainenceSettings',
    societyDues:'SocietyDues',
    flatsOnboarding:'FlatsOnboarding',
    editOnboardedFlatDetails:'EditOnboardedFlatDetails',
    notification:"Notification",
    adminFlatSettings:'AdminFlatSettings',
    expences:'Expences',
    addNewExpances:'AddNewExpances',
    coAdmin:'CoAdmin',
  },
  months :[
    {name: 'January', index: 1},
    {name: 'February', index: 2},
    {name: 'March', index: 3},
    {name: 'April', index: 4},
    {name: 'May', index: 5},
    {name: 'June', index: 6},
    {name: 'July', index: 7},
    {name: 'August', index: 8},
    {name: 'September', index: 9},
    {name: 'October', index: 10},
    {name: 'November', index: 11},
    {name: 'December', index: 12},
  ]
};
